version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
    env_file: .env
    volumes:
      - .:/opt/marblecutter/
      - ../marblecutter/marblecutter:/usr/local/lib/python3.6/dist-packages/marblecutter
    ports:
      - "8000:8000"
    entrypoint: python
    command: server.py
